# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-24 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20190124_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rango.Category'),
        ),
    ]
